language: ruby
rvm:
  - '2.3.0'

addons:
  postgresql: "9.3"

services:
  - redis-server

gemfile:
  - Gemfile

matrix:

before_script:
  - psql -c 'create database lintci_test;' -U postgres
  - bundle exec rake db:setup

notifications:
  email: false
