language: ruby
rvm:
  - '2.2.2'

addons:
  postgresql: "9.3"

gemfile:
  - Gemfile

matrix:

before_script:
  - psql -c 'create database lintci_test;' -U postgres
  - RAILS_ENV=test bundle exec rake db:migrate

notifications:
  email: false
