development: &default
  adapter: postgresql
  database: lintci_development
  pool: 5

test:
  <<: *default
  database: lintci_test

production:
  <<: *default
  database: lintci_production
  host: <%= ENV['LINTCI_DATABASE_URL'] %>
  username: <%= ENV['LINTCI_DATABASE_USERNAME'] %>
  password: <%= ENV['LINTCI_DATABASE_PASSWORD'] %>
